"""
Django settings for serverapp project.

Generated by 'django-admin startproject' using Django 2.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import pathlib

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'x!w0j(8lyq2s1k=hkl2*rdeq3-$&s6)1j2cu)@&9f&=5^%91yt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ['localhost']
CSRF_TRUSTED_ORIGINS = ['localhost']
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

# Application definition

INSTALLED_APPS = [
    'editor',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'serverapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'serverapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'de-de'

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

# Email Config
EMAIL_HOST = 'host'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'user'
EMAIL_HOST_PASSWORD = 'pwd'
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'from@email.com'



# Here comes the custom configuration of the editor
dir_root = pathlib.Path(os.path.dirname(os.path.realpath(__file__))).parent.parent
CUSTOM = {
    "domain": "localhost", # domain used for non-relative links e.g. in emails
    "base_url": "tptp_editor", # top-level url
    "protocol": "http", # protocol used for non-relative links e.g. in emails
    "filesystem": "disk_filesystem",
    "filesystem_parameters": [pathlib.Path("/","home","tg","fs")],
    "login_required": True, # true if users have to login - false if users do not login and share the same environment
    "treelimitedrun_binary": dir_root.joinpath("bin", "TreeLimitedRun"),
    "allow_custom_local_provers": True,
    "predefined_local_provers": [
        {
            "name": "leo3_on_uberspace",
            "command": "/home/waschbae/java/jdk1.8.0_192/bin/java",
            "parameters": "-jar /home/waschbae/leo3.jar %s -t %d",
            "dialects": ["TH0", "TH1", "CNF", "FOF"]
        },
        {
            "name": "leo3_at_home",
            "command": "leo3",
            "parameters": "%s -t %d",
            "dialects": ["TH0", "TH1", "CNF", "FOF"]
        }
    ],
    "embedding_binary": dir_root.joinpath("bin", "embedlogic"),
    "predefined_embeddings": [
        {
            "name": "standard_s5",
            "consequences": "$local",
            "constants": "$rigid",
            "domains": "$constant",
            "modalities": "$modal_system_S5",
            "parameters": ""
        },
        {
            "name": "varying_s5",
            "consequences": "$local",
            "constants": "$rigid",
            "domains": "[$constant, $i := $varying]",
            "modalities": "$modal_system_S5",
            "parameters": ""
        }
    ],
    "predefined_latex_export_configurations": [
        {
            "name": "standard",
            "file": dir_root.joinpath("webapp","serverapp", "latex_configuration_standard.json")
        },
        {
            "name": "modal_logic",
            "file": dir_root.joinpath("webapp","serverapp", "latex_configuration_modal_logic.json")
        }
    ]
}
CUSTOM['base_url'] = CUSTOM['base_url'].strip('/')
BASE_URL = "/" + CUSTOM['base_url']
LOGIN_REDIRECT_URL = BASE_URL
